version: "3"
services:
  hostmachine_0:
    build: .
    image: machine_0
    ports:
     - "2222:22"
    networks:
      - network0
  hostmachine_1:
    build: .
    image: machine_1
    networks:
      - network0
  hostdevice_2:
    build: .
    image: device_2
    networks:
      - network1
      - network0
  hostmachine_3:
    build: .
    image: machine_3
    networks:
      - network0
  hostmachine_4:
    build: .
    image: machine_4
    networks:
      - network2
  hostdevice_5:
    build: .
    image: device_5
    networks:
      - network3
      - network2
  hostmachine_6:
    build: .
    image: machine_6
    networks:
      - network3
  hostmachine_7:
    build: .
    image: machine_7
    networks:
      - network3
  hostmachine_8:
    build: .
    image: machine_8
    networks:
      - network2
  hostmachine_9:
    build: .
    image: machine_9
    networks:
      - network2
  hostmachine_10:
    build: .
    image: machine_10
    networks:
      - network2
  hostmachine_11:
    build: .
    image: machine_11
    networks:
      - network4
  hostmachine_12:
    build: .
    image: machine_12
    networks:
      - network4
  hostdevice_13:
    build: .
    image: device_13
    networks:
      - network5
      - network4
  hostmachine_14:
    build: .
    image: machine_14
    networks:
      - network5
  hostmachine_15:
    build: .
    image: machine_15
    networks:
      - network5
  hostmachine_16:
    build: .
    image: machine_16
    networks:
      - network5
  hostmachine_17:
    build: .
    image: machine_17
    networks:
      - network5
  hostmachine_18:
    build: .
    image: machine_18
    networks:
      - network4
  hostdevice_19:
    build: .
    image: device_19
    networks:
      - network6
      - network4
  hostmachine_20:
    build: .
    image: machine_20
    networks:
      - network6
  hostmachine_21:
    build: .
    image: machine_21
    networks:
      - network6
  hostmachine_22:
    build: .
    image: machine_22
    networks:
      - network4
  hostdevice_23:
    build: .
    image: device_23
    networks:
      - network7
      - network4
  hostdevice_24:
    build: .
    image: device_24
    networks:
      - network8
      - network7
  hostmachine_25:
    build: .
    image: machine_25
    networks:
      - network4

################ NETWORKING ################
networks:

  network0:
    driver: bridge

  network1:
    driver: bridge

  network2:
    driver: bridge

  network3:
    driver: bridge

  network4:
    driver: bridge

  network5:
    driver: bridge

  network6:
    driver: bridge

  network7:
    driver: bridge

  network8:
    driver: bridge

