version: "3"
services:
  hostmachine_0:
    build: .
    image: machine_0
    networks:
      - network0
  hostdevice_1:
    build: .
    image: device_1
    networks:
      - network1
      - network0
  hostmachine_2:
    build: .
    image: machine_2
    networks:
      - network1
  hostmachine_3:
    build: .
    image: machine_3
    networks:
      - network1
  hostmachine_4:
    build: .
    image: machine_4
    networks:
      - network1
  hostmachine_5:
    build: .
    image: machine_5
    networks:
      - network1
  hostdevice_6:
    build: .
    image: device_6
    networks:
      - network2
      - network0
  hostmachine_7:
    build: .
    image: machine_7
    networks:
      - network2
  hostdevice_8:
    build: .
    image: device_8
    networks:
      - network3
      - network2
  hostdevice_9:
    build: .
    image: device_9
    networks:
      - network4
      - network2
  hostdevice_10:
    build: .
    image: device_10
    networks:
      - network5
      - network2
  hostdevice_11:
    build: .
    image: device_11
    networks:
      - network6
      - network5
  hostdevice_12:
    build: .
    image: device_12
    networks:
      - network7
      - network6
  hostdevice_13:
    build: .
    image: device_13
    networks:
      - network8
      - network6
  hostmachine_14:
    build: .
    image: machine_14
    networks:
      - network6
  hostmachine_15:
    build: .
    image: machine_15
    networks:
      - network6
  hostdevice_16:
    build: .
    image: device_16
    networks:
      - network9
      - network6
  hostdevice_17:
    build: .
    image: device_17
    networks:
      - network10
      - network6
  hostmachine_18:
    build: .
    image: machine_18
    networks:
      - network6
  hostdevice_19:
    build: .
    image: device_19
    networks:
      - network11
      - network5
  hostdevice_20:
    build: .
    image: device_20
    networks:
      - network12
      - network11
  hostdevice_21:
    build: .
    image: device_21
    networks:
      - network13
      - network12
  hostdevice_22:
    build: .
    image: device_22
    networks:
      - network14
      - network2
  hostmachine_23:
    build: .
    image: machine_23
    networks:
      - network2
  hostdevice_24:
    build: .
    image: device_24
    networks:
      - network15
      - network2
  hostdevice_25:
    build: .
    image: device_25
    networks:
      - network16
      - network2
  hostdevice_26:
    build: .
    image: device_26
    networks:
      - network17
      - network2
  hostdevice_27:
    build: .
    image: device_27
    networks:
      - network18
      - network2
  hostmachine_28:
    build: .
    image: machine_28
    networks:
      - network0
  hostdevice_29:
    build: .
    image: device_29
    networks:
      - network19
      - network0
  hostdevice_30:
    build: .
    image: device_30
    networks:
      - network20
      - network19
  hostdevice_31:
    build: .
    image: device_31
    networks:
      - network21
      - network19
  hostdevice_32:
    build: .
    image: device_32
    networks:
      - network22
      - network19
  hostdevice_33:
    build: .
    image: device_33
    networks:
      - network23
      - network22
  hostdevice_34:
    build: .
    image: device_34
    networks:
      - network24
      - network22
  hostdevice_35:
    build: .
    image: device_35
    networks:
      - network25
      - network22
  hostdevice_36:
    build: .
    image: device_36
    networks:
      - network26
      - network25
  hostdevice_37:
    build: .
    image: device_37
    networks:
      - network27
      - network26
  hostdevice_38:
    build: .
    image: device_38
    networks:
      - network28
      - network26
  hostmachine_39:
    build: .
    image: machine_39
    networks:
      - network26
  hostmachine_40:
    build: .
    image: machine_40
    networks:
      - network26
  hostdevice_41:
    build: .
    image: device_41
    networks:
      - network29
      - network25
  hostdevice_42:
    build: .
    image: device_42
    networks:
      - network30
      - network29
  hostdevice_43:
    build: .
    image: device_43
    networks:
      - network31
      - network29
  hostdevice_44:
    build: .
    image: device_44
    networks:
      - network32
      - network29
  hostmachine_45:
    build: .
    image: machine_45
    networks:
      - network32
  hostdevice_46:
    build: .
    image: device_46
    networks:
      - network33
      - network32
  hostdevice_47:
    build: .
    image: device_47
    networks:
      - network34
      - network32
  hostmachine_48:
    build: .
    image: machine_48
    networks:
      - network32
  hostdevice_49:
    build: .
    image: device_49
    networks:
      - network35
      - network32
  hostdevice_50:
    build: .
    image: device_50
    networks:
      - network36
      - network32
  hostdevice_51:
    build: .
    image: device_51
    networks:
      - network37
      - network29
  hostdevice_52:
    build: .
    image: device_52
    networks:
      - network38
      - network0
  hostdevice_53:
    build: .
    image: device_53
    networks:
      - network39
      - network38
  hostdevice_54:
    build: .
    image: device_54
    networks:
      - network40
      - network38
  hostdevice_55:
    build: .
    image: device_55
    networks:
      - network41
      - network38
  hostdevice_56:
    build: .
    image: device_56
    networks:
      - network42
      - network0
  hostdevice_57:
    build: .
    image: device_57
    networks:
      - network43
      - network42
  hostmachine_58:
    build: .
    image: machine_58
    networks:
      - network43
  hostdevice_59:
    build: .
    image: device_59
    networks:
      - network44
      - network43
  hostdevice_60:
    build: .
    image: device_60
    networks:
      - network45
      - network43
  hostdevice_61:
    build: .
    image: device_61
    networks:
      - network46
      - network43
  hostmachine_62:
    build: .
    image: machine_62
    networks:
      - network43
  hostdevice_63:
    build: .
    image: device_63
    networks:
      - network47
      - network43
  hostdevice_64:
    build: .
    image: device_64
    networks:
      - network48
      - network43
  hostmachine_65:
    build: .
    image: machine_65
    networks:
      - network43
  hostmachine_66:
    build: .
    image: machine_66
    networks:
      - network0

################ NETWORKING ################
networks:

  network0:
    driver: bridge
  network1:
    driver: bridge
    internal
  network2:
    driver: bridge
    internal
  network3:
    driver: bridge
    internal
  network4:
    driver: bridge
    internal
  network5:
    driver: bridge
    internal
  network6:
    driver: bridge
    internal
  network7:
    driver: bridge
    internal
  network8:
    driver: bridge
    internal
  network9:
    driver: bridge
    internal
  network10:
    driver: bridge
    internal
  network11:
    driver: bridge
    internal
  network12:
    driver: bridge
    internal
  network13:
    driver: bridge
    internal
  network14:
    driver: bridge
    internal
  network15:
    driver: bridge
    internal
  network16:
    driver: bridge
    internal
  network17:
    driver: bridge
    internal
  network18:
    driver: bridge
    internal
  network19:
    driver: bridge
    internal
  network20:
    driver: bridge
    internal
  network21:
    driver: bridge
    internal
  network22:
    driver: bridge
    internal
  network23:
    driver: bridge
    internal
  network24:
    driver: bridge
    internal
  network25:
    driver: bridge
    internal
  network26:
    driver: bridge
    internal
  network27:
    driver: bridge
    internal
  network28:
    driver: bridge
    internal
  network29:
    driver: bridge
    internal
  network30:
    driver: bridge
    internal
  network31:
    driver: bridge
    internal
  network32:
    driver: bridge
    internal
  network33:
    driver: bridge
    internal
  network34:
    driver: bridge
    internal
  network35:
    driver: bridge
    internal
  network36:
    driver: bridge
    internal
  network37:
    driver: bridge
    internal
  network38:
    driver: bridge
    internal
  network39:
    driver: bridge
    internal
  network40:
    driver: bridge
    internal
  network41:
    driver: bridge
    internal
  network42:
    driver: bridge
    internal
  network43:
    driver: bridge
    internal
  network44:
    driver: bridge
    internal
  network45:
    driver: bridge
    internal
  network46:
    driver: bridge
    internal
  network47:
    driver: bridge
    internal
  network48:
    driver: bridge
    internal
